baseURL = '/'  # 일단 이렇게, 나중에 배포하면 Netlify URL로
copyright = "2025"
languageCode = 'ko-KR'  # 한국어로 변경
defaultContentLanguage = 'en'  # 한국어로
theme = 'enchanted-lowkey'
title = 'violet watcher'
enableRobotsTXT = true
summaryLength = 15
pagination.pagerSize = 5

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4