[[main]]
#    identifier = "home"
#    name = "Home"
#    url = "/posts"
#    weight = 1

[[main]]
    identifier = "posts"
    name = "POSTS"
    url = "/posts"
    weight = 1

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3

# Social Media Configuration

[[social]]
#    identifier = "twitter"
#    name = "Twitter"
#    url = "#"
#    weight = 1

[[social]]
#    identifier = "instagram"
#    name = "Instagram"
#    url = "#"
#    weight = 2

[[social]]
#    identifier = "github"
#    name = "GitHub"
#    url = "#"
#    weight = 3